name: env_mri_s2d
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - certifi=2023.11.17=py38h06a4308_0
  - cffi=1.16.0=py38h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=41.0.7=py38hdda0065_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.3.101=0
  - cuda-runtime=12.1.0=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py38h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py38h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.2=py38h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.107=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py38h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py38h06a4308_0
  - numpy=1.24.3=py38hf6e8229_1
  - numpy-base=1.24.3=py38h060ed82_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.12=h7f8727e_0
  - pillow=10.0.1=py38ha6cbd5a_0
  - pip=23.3.1=py38h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - pytorch=2.1.2=py3.8_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py38h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py38h06a4308_0
  - setuptools=68.2.2=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py38h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.1.2=py38_cu121
  - torchtriton=2.1.0=py38
  - torchvision=0.16.2=py38_cu121
  - typing_extensions=4.9.0=py38h06a4308_0
  - urllib3=1.26.18=py38h06a4308_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.0.0
      - addict==2.4.0
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - anyio==4.2.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrdict==2.0.1
      - attrs==23.2.0
      - babel==2.14.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - blinker==1.8.2
      - cachetools==5.3.2
      - click==8.1.7
      - colorama==0.4.6
      - comm==0.2.1
      - configargparse==1.7
      - contourpy==1.1.1
      - coverage==7.4.3
      - cycler==0.12.1
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - debugpy==1.8.0
      - decorator==5.1.1
      - deepali==0.1
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - dicom-numpy==0.6.5
      - edt==2.4.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - flask==3.0.3
      - fonttools==4.47.2
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2023.12.2
      - google-auth==2.26.2
      - google-auth-oauthlib==1.0.0
      - grpcio==1.60.0
      - humanize==4.9.0
      - imageio==2.34.0
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.1
      - iniconfig==2.0.0
      - ipykernel==6.29.0
      - ipython==8.12.3
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - itk==5.3.0
      - itk-core==5.3.0
      - itk-filtering==5.3.0
      - itk-io==5.3.0
      - itk-numerics==5.3.0
      - itk-registration==5.3.0
      - itk-segmentation==5.3.0
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.21.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.0
      - jupyter-console==6.6.3
      - jupyter-core==5.7.1
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.1
      - jupyter-server==2.12.5
      - jupyter-server-terminals==0.5.1
      - jupyterlab==4.0.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.2
      - jupyterlab-widgets==3.0.9
      - kaleido==0.2.1
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - lightning-utilities==0.10.0
      - markdown==3.5.2
      - markdown-it-py==3.0.0
      - matplotlib==3.7.4
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - medio==0.4.2
      - medutils==0.1.21
      - mistune==3.0.2
      - monai==1.3.1
      - multidict==6.0.4
      - nbclient==0.9.0
      - nbconvert==7.14.2
      - nbformat==5.9.2
      - nest-asyncio==1.5.9
      - nibabel==3.2.2
      - notebook==7.0.6
      - notebook-shim==0.2.3
      - nptyping==2.5.0
      - oauthlib==3.2.2
      - open3d==0.19.0
      - opencv-python==4.9.0.80
      - overrides==7.4.0
      - packaging==23.2
      - pandas==2.0.3
      - pandas-flavor==0.6.0
      - pandocfilters==1.5.0
      - parameterized==0.9.0
      - parso==0.8.3
      - patsy==0.5.6
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pingouin==0.5.4
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.1.0
      - plotly==5.20.0
      - pluggy==1.4.0
      - pooch==1.8.2
      - prometheus-client==0.19.0
      - prompt-toolkit==3.0.43
      - protobuf==4.25.2
      - psutil==5.9.7
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycad==0.0.0.1
      - pydicom==2.4.4
      - pyglet==2.0.18
      - pygments==2.17.2
      - pynrrd==1.0.0
      - pyparsing==3.1.1
      - pyquaternion==0.9.9
      - pyserial==3.5
      - pysimplegui==5.0.2
      - pytest==8.0.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytorch-lightning==2.1.3
      - pytz==2023.3.post1
      - pyvista==0.43.9
      - pywavelets==1.4.1
      - pyzmq==25.1.2
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - referencing==0.32.1
      - requests-oauthlib==1.3.1
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.0
      - rpds-py==0.17.1
      - rsa==4.9
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - scooby==0.10.0
      - seaborn==0.13.1
      - seg-metrics==1.1.6
      - send2trash==1.8.2
      - shellingham==1.5.4
      - simpleitk==1.2.4
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - statsmodels==0.14.1
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - terminado==0.18.0
      - threadpoolctl==3.2.0
      - tifffile==2023.7.10
      - tinycss2==1.2.1
      - tomli==2.0.1
      - torchio==0.19.3
      - torchmetrics==1.3.0
      - tornado==6.4
      - tqdm==4.66.1
      - traitlets==5.14.1
      - trimesh==4.4.0
      - typer==0.9.0
      - types-python-dateutil==2.8.19.20240106
      - tzdata==2023.4
      - uri-template==1.3.0
      - vtk==9.3.0
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.9
      - wrapt==1.16.0
      - xarray==2023.1.0
      - yarl==1.9.4
      - zipp==3.17.0
prefix: /home/yx22/anaconda3/envs/env_mri_s2d
